name: 'CI-Pipeline'

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: CI-Pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: CI-(Setup .NET)
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: CI-(Restore dependencies)
      run: dotnet restore
    - name: CI-Build
      run: dotnet build --no-restore
    - name: CI-Test
      run: dotnet test --no-build --verbosity normal
