name: dotnet test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Test
      run: dotnet test --verbosity normal
            
    - name: Test Report
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: jest-junit.xml
