name: 'Test Report'
on:
  workflow_run:
    workflows: ['dotnet-test']                     # runs after dotnet-test workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: dotnet tests                # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results
